---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "90%",
  out.height = "90%",
  fig.retina = 2
)
```

# specProc

<!-- badges: start -->

<!-- badges: end -->

`specProc` package performs a number of pre-processing tasks commonly used in the analysis of laser-induced breakdown spectroscopy (LIBS) spectra. Collectively, these are essential tools in LIBS calibration modeling, called chemometrics. These include:

-   Baseline removal
-   Peaks detection
-   Fitting single, multiple or overlapping peaks
-   Spectral-based normalization 
-   Smoothing and filtering
-   Robust or classical Box-Cox transformation 
-   Pearson or Spearman peaks correlation
-   Descriptive statistics such as mean, standard deviation and higher
    central moments 
-   Statistical tests
-   Rowwise and cellwise outliers detection
-   Robust or classical principal component analysis (PCA)
-   Orthogonal partial-least squares (OPLS)
-   PLS-based wavelength selection


## Installation

You can install the development version from
[GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ChristianGoueguel/specProc")
```
