hexSticker::sticker(
  subplot = "~/Documents/Packages/specProc/bkg.png",
  package = "specProc",
  p_y = 1.5,
  p_x = 1,
  p_size = 27,
  p_color = "gold",
  s_x = 1,
  s_y = 0.8,
  s_width = 0.8,
  s_height = 0.5,
  h_fill = "black",
  h_color = "#F2AA4CFF",
  url = "https://github.com/ChristianGoueguel/specProc",
  u_color = "gold",
  u_size = 3.5,
  spotlight = FALSE,
  l_x = 0.9,
  l_y = 0.8,
  l_width = 20,
  l_alpha = 0.5,
  filename = "inst/figures/pkg_sticker.png",
)

usethis::use_logo(img = "inst/figures/pkg_sticker.png", geometry = "250x300", retina = TRUE)
