# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeGroupedMeans <- function(data, group) {
    .Call(`_specProc_computeGroupedMeans`, data, group)
}

computeMeans <- function(data) {
    .Call(`_specProc_computeMeans`, data)
}

epo_cpp <- function(X, ncomp) {
    .Call(`_specProc_epo_cpp`, X, ncomp)
}

glsw_cpp <- function(X_diff, alpha) {
    .Call(`_specProc_glsw_cpp`, X_diff, alpha)
}

