# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whittaker_baseline_cpp <- function(x, lambda, param, max_iter, method) {
    .Call(`_specProc_whittaker_baseline_cpp`, x, lambda, param, max_iter, method)
}

col_medians_cpp <- function(x, na_rm) {
    .Call(`_specProc_col_medians_cpp`, x, na_rm)
}

computeGroupedMeans <- function(data, group, ngroups) {
    .Call(`_specProc_computeGroupedMeans`, data, group, ngroups)
}

computeMeans <- function(data) {
    .Call(`_specProc_computeMeans`, data)
}

ddc_neighbors_cpp <- function(u, corrlim, maxnb, min_abs, block) {
    .Call(`_specProc_ddc_neighbors_cpp`, u, corrlim, maxnb, min_abs, block)
}

ddc_predict_cpp <- function(u, index, correlation, slope) {
    .Call(`_specProc_ddc_predict_cpp`, u, index, correlation, slope)
}

epo_cpp <- function(X, D, ncomp) {
    .Call(`_specProc_epo_cpp`, X, D, ncomp)
}

glsw_cpp <- function(X_diff, alpha) {
    .Call(`_specProc_glsw_cpp`, X_diff, alpha)
}

univariate_mcd_cpp <- function(x, h) {
    .Call(`_specProc_univariate_mcd_cpp`, x, h)
}

sd_outlyingness_cpp <- function(z, h, ndir) {
    .Call(`_specProc_sd_outlyingness_cpp`, z, h, ndir)
}

fast_mcd_cpp <- function(x, h, nsamp) {
    .Call(`_specProc_fast_mcd_cpp`, x, h, nsamp)
}

spca_grid_cpp <- function(x_in, k, lambda, ngrid, maxiter, tol) {
    .Call(`_specProc_spca_grid_cpp`, x_in, k, lambda, ngrid, maxiter, tol)
}

som_batch_cpp <- function(x, init, grid_dist2, sigma, robust, huber_c) {
    .Call(`_specProc_som_batch_cpp`, x, init, grid_dist2, sigma, robust, huber_c)
}

som_map_cpp <- function(x, codebook) {
    .Call(`_specProc_som_map_cpp`, x, codebook)
}

voigt_cpp <- function(x, sigma, gamma) {
    .Call(`_specProc_voigt_cpp`, x, sigma, gamma)
}

yGradientglswCpp <- function(X_diff, w_i, alpha) {
    .Call(`_specProc_yGradientglswCpp`, X_diff, w_i, alpha)
}

