# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whittaker_baseline_cpp <- function(x, lambda, param, max_iter, method) {
    .Call(`_specProc_whittaker_baseline_cpp`, x, lambda, param, max_iter, method)
}

scale_tanh_cols_cpp <- function(x) {
    .Call(`_specProc_scale_tanh_cols_cpp`, x)
}

rho_tanh_cpp <- function(z, b1 = 1.5) {
    .Call(`_specProc_rho_tanh_cpp`, z, b1)
}

cellpca_irls_cpp <- function(x, m, V0, U0, mu0, sigma1, sigma2, par2, b1, maxiter, tol, max_col_frac) {
    .Call(`_specProc_cellpca_irls_cpp`, x, m, V0, U0, mu0, sigma1, sigma2, par2, b1, maxiter, tol, max_col_frac)
}

cellpca_predict_cpp <- function(x, m, V, mu, sigma1, b1, maxiter, tol) {
    .Call(`_specProc_cellpca_predict_cpp`, x, m, V, mu, sigma1, b1, maxiter, tol)
}

col_medians_cpp <- function(x, na_rm) {
    .Call(`_specProc_col_medians_cpp`, x, na_rm)
}

computeGroupedMeans <- function(data, group, ngroups) {
    .Call(`_specProc_computeGroupedMeans`, data, group, ngroups)
}

computeMeans <- function(data) {
    .Call(`_specProc_computeMeans`, data)
}

ddc_core_cpp <- function(x, tol_prob, corrlim, maxnb, fast, block) {
    .Call(`_specProc_ddc_core_cpp`, x, tol_prob, corrlim, maxnb, fast, block)
}

ddc_apply_cpp <- function(x, loc, scale, ngbrs, weights, slopes, deshrink, res_scale, standalone, tol_prob, med_ti, mad_ti) {
    .Call(`_specProc_ddc_apply_cpp`, x, loc, scale, ngbrs, weights, slopes, deshrink, res_scale, standalone, tol_prob, med_ti, mad_ti)
}

unimcd_cpp <- function(x, alpha) {
    .Call(`_specProc_unimcd_cpp`, x, alpha)
}

scale_1step_cols_cpp <- function(x) {
    .Call(`_specProc_scale_1step_cols_cpp`, x)
}

univariate_mcd_cpp <- function(x, h) {
    .Call(`_specProc_univariate_mcd_cpp`, x, h)
}

sd_outlyingness_cpp <- function(z, h, ndir) {
    .Call(`_specProc_sd_outlyingness_cpp`, z, h, ndir)
}

fast_mcd_cpp <- function(x, h, nsamp) {
    .Call(`_specProc_fast_mcd_cpp`, x, h, nsamp)
}

spca_grid_cpp <- function(x_in, k, lambda, ngrid, maxiter, tol) {
    .Call(`_specProc_spca_grid_cpp`, x_in, k, lambda, ngrid, maxiter, tol)
}

som_batch_cpp <- function(x, init, grid_dist2, sigma, robust, huber_c) {
    .Call(`_specProc_som_batch_cpp`, x, init, grid_dist2, sigma, robust, huber_c)
}

som_map_cpp <- function(x, codebook) {
    .Call(`_specProc_som_map_cpp`, x, codebook)
}

voigt_cpp <- function(x, sigma, gamma) {
    .Call(`_specProc_voigt_cpp`, x, sigma, gamma)
}

